<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\PublicHoliday;
use Carbon\Carbon;

class PublicHolidaySeeder extends Seeder
{
    public function run(): void
    {
        $holidays = [
            // ========================================
            // GLOBAL/INTERNATIONAL HOLIDAYS
            // ========================================
            [
                'country_code' => null,
                'title' => "New Year's Day",
                'description' => 'Celebration of the first day of the new year',
                'date' => Carbon::create(2025, 1, 1),
                'recurring' => true,
                'recurrence_type' => 1,
                'month' => 1,
                'day' => 1,
                'color' => '#ef4444',
                'is_active' => true,
            ],
            [
                'country_code' => null,
                'title' => 'International Workers Day',
                'description' => 'May Day - Celebration of workers and labor movement',
                'date' => Carbon::create(2025, 5, 1),
                'recurring' => true,
                'recurrence_type' => 1,
                'month' => 5,
                'day' => 1,
                'color' => '#3b82f6',
                'is_active' => true,
            ],
            [
                'country_code' => null,
                'title' => 'Christmas Day',
                'description' => 'Christmas celebration',
                'date' => Carbon::create(2025, 12, 25),
                'recurring' => true,
                'recurrence_type' => 1,
                'month' => 12,
                'day' => 25,
                'color' => '#22c55e',
                'is_active' => true,
            ],

            // ========================================
            // UNITED STATES SCHOOL HOLIDAYS
            // ========================================
            [
                'country_code' => 'US',
                'title' => 'Martin Luther King Jr. Day',
                'description' => 'Honors civil rights leader Martin Luther King Jr. (Third Monday in January)',
                'date' => Carbon::create(2025, 1, 20),
                'recurring' => true,
                'recurrence_type' => 1,
                'month' => 1,
                'day' => 20,
                'color' => '#6366f1',
                'is_active' => true,
            ],
            [
                'country_code' => 'US',
                'title' => "Presidents' Day",
                'description' => 'Honors all US Presidents (Third Monday in February)',
                'date' => Carbon::create(2025, 2, 17),
                'recurring' => true,
                'recurrence_type' => 1,
                'month' => 2,
                'day' => 17,
                'color' => '#3b82f6',
                'is_active' => true,
            ],
            [
                'country_code' => 'US',
                'title' => 'Memorial Day',
                'description' => 'Honors military personnel who died in service (Last Monday in May)',
                'date' => Carbon::create(2025, 5, 26),
                'recurring' => true,
                'recurrence_type' => 1,
                'month' => 5,
                'day' => 26,
                'color' => '#dc2626',
                'is_active' => true,
            ],
            [
                'country_code' => 'US',
                'title' => 'Independence Day',
                'description' => 'United States Independence Day',
                'date' => Carbon::create(2025, 7, 4),
                'recurring' => true,
                'recurrence_type' => 1,
                'month' => 7,
                'day' => 4,
                'color' => '#ef4444',
                'is_active' => true,
            ],
            [
                'country_code' => 'US',
                'title' => 'Labor Day',
                'description' => 'Celebrates workers and labor movement (First Monday in September)',
                'date' => Carbon::create(2025, 9, 1),
                'recurring' => true,
                'recurrence_type' => 1,
                'month' => 9,
                'day' => 1,
                'color' => '#3b82f6',
                'is_active' => true,
            ],
            [
                'country_code' => 'US',
                'title' => 'Columbus Day',
                'description' => 'Marks Christopher Columbus arrival in Americas (Second Monday in October)',
                'date' => Carbon::create(2025, 10, 13),
                'recurring' => true,
                'recurrence_type' => 1,
                'month' => 10,
                'day' => 13,
                'color' => '#8b5cf6',
                'is_active' => true,
            ],
            [
                'country_code' => 'US',
                'title' => 'Veterans Day',
                'description' => 'Honors all military veterans',
                'date' => Carbon::create(2025, 11, 11),
                'recurring' => true,
                'recurrence_type' => 1,
                'month' => 11,
                'day' => 11,
                'color' => '#dc2626',
                'is_active' => true,
            ],
            [
                'country_code' => 'US',
                'title' => 'Thanksgiving Day',
                'description' => 'Thanksgiving holiday (Fourth Thursday in November)',
                'date' => Carbon::create(2025, 11, 27),
                'recurring' => true,
                'recurrence_type' => 1,
                'month' => 11,
                'day' => 27,
                'color' => '#f97316',
                'is_active' => true,
            ],

            // ========================================
            // INDIA SCHOOL HOLIDAYS
            // ========================================
            [
                'country_code' => 'IN',
                'title' => 'Republic Day',
                'description' => 'India Republic Day - Constitution of India came into effect',
                'date' => Carbon::create(2025, 1, 26),
                'recurring' => true,
                'recurrence_type' => 1,
                'month' => 1,
                'day' => 26,
                'color' => '#ef4444',
                'is_active' => true,
            ],
            [
                'country_code' => 'IN',
                'title' => 'Makar Sankranti',
                'description' => 'Harvest festival marking the transition of the sun',
                'date' => Carbon::create(2025, 1, 14),
                'recurring' => true,
                'recurrence_type' => 1,
                'month' => 1,
                'day' => 14,
                'color' => '#facc15',
                'is_active' => true,
            ],
            [
                'country_code' => 'IN',
                'title' => 'Holi',
                'description' => 'Festival of Colors - Spring festival',
                'date' => Carbon::create(2025, 3, 14),
                'recurring' => true,
                'recurrence_type' => 1,
                'month' => 3,
                'day' => 14,
                'color' => '#facc15',
                'is_active' => true,
            ],
            [
                'country_code' => 'IN',
                'title' => 'Good Friday',
                'description' => 'Christian holiday commemorating the crucifixion of Jesus',
                'date' => Carbon::create(2025, 4, 18),
                'recurring' => true,
                'recurrence_type' => 1,
                'month' => 4,
                'day' => 18,
                'color' => '#8b5cf6',
                'is_active' => true,
            ],
            [
                'country_code' => 'IN',
                'title' => 'Eid ul-Fitr',
                'description' => 'Festival marking the end of Ramadan',
                'date' => Carbon::create(2025, 3, 31),
                'recurring' => true,
                'recurrence_type' => 1,
                'month' => 3,
                'day' => 31,
                'color' => '#22c55e',
                'is_active' => true,
            ],
            [
                'country_code' => 'IN',
                'title' => 'Independence Day',
                'description' => 'India Independence Day - Freedom from British rule',
                'date' => Carbon::create(2025, 8, 15),
                'recurring' => true,
                'recurrence_type' => 1,
                'month' => 8,
                'day' => 15,
                'color' => '#ef4444',
                'is_active' => true,
            ],
            [
                'country_code' => 'IN',
                'title' => 'Raksha Bandhan',
                'description' => 'Festival celebrating the bond between brothers and sisters',
                'date' => Carbon::create(2025, 8, 9),
                'recurring' => true,
                'recurrence_type' => 1,
                'month' => 8,
                'day' => 9,
                'color' => '#ec4899',
                'is_active' => true,
            ],
            [
                'country_code' => 'IN',
                'title' => 'Janmashtami',
                'description' => 'Birthday of Lord Krishna',
                'date' => Carbon::create(2025, 8, 26),
                'recurring' => true,
                'recurrence_type' => 1,
                'month' => 8,
                'day' => 26,
                'color' => '#facc15',
                'is_active' => true,
            ],
            [
                'country_code' => 'IN',
                'title' => 'Ganesh Chaturthi',
                'description' => 'Festival celebrating the birth of Lord Ganesha',
                'date' => Carbon::create(2025, 8, 27),
                'recurring' => true,
                'recurrence_type' => 1,
                'month' => 8,
                'day' => 27,
                'color' => '#facc15',
                'is_active' => true,
            ],
            [
                'country_code' => 'IN',
                'title' => 'Dussehra',
                'description' => 'Festival celebrating the victory of good over evil',
                'date' => Carbon::create(2025, 10, 2),
                'recurring' => true,
                'recurrence_type' => 1,
                'month' => 10,
                'day' => 2,
                'color' => '#facc15',
                'is_active' => true,
            ],
            [
                'country_code' => 'IN',
                'title' => 'Gandhi Jayanti',
                'description' => 'Birthday of Mahatma Gandhi - Father of the Nation',
                'date' => Carbon::create(2025, 10, 2),
                'recurring' => true,
                'recurrence_type' => 1,
                'month' => 10,
                'day' => 2,
                'color' => '#ef4444',
                'is_active' => true,
            ],
            [
                'country_code' => 'IN',
                'title' => 'Diwali',
                'description' => 'Festival of Lights - Most important Hindu festival',
                'date' => Carbon::create(2025, 10, 20),
                'recurring' => true,
                'recurrence_type' => 1,
                'month' => 10,
                'day' => 20,
                'color' => '#facc15',
                'is_active' => true,
            ],
            [
                'country_code' => 'IN',
                'title' => 'Eid ul-Adha',
                'description' => 'Festival of Sacrifice - Islamic holiday',
                'date' => Carbon::create(2025, 6, 17),
                'recurring' => true,
                'recurrence_type' => 1,
                'month' => 6,
                'day' => 17,
                'color' => '#22c55e',
                'is_active' => true,
            ],
            // Note: "Christmas Day" is already in global holidays

            // ========================================
            // UNITED KINGDOM SCHOOL HOLIDAYS
            // ========================================
            // Note: "New Year's Day" and "Christmas Day" are already in global holidays
            [
                'country_code' => 'GB',
                'title' => 'Good Friday',
                'description' => 'Christian holiday commemorating the crucifixion of Jesus',
                'date' => Carbon::create(2025, 4, 18),
                'recurring' => true,
                'recurrence_type' => 1,
                'month' => 4,
                'day' => 18,
                'color' => '#8b5cf6',
                'is_active' => true,
            ],
            [
                'country_code' => 'GB',
                'title' => 'Easter Monday',
                'description' => 'Day after Easter Sunday',
                'date' => Carbon::create(2025, 4, 21),
                'recurring' => true,
                'recurrence_type' => 1,
                'month' => 4,
                'day' => 21,
                'color' => '#8b5cf6',
                'is_active' => true,
            ],
            [
                'country_code' => 'GB',
                'title' => 'Early May Bank Holiday',
                'description' => 'First Monday in May',
                'date' => Carbon::create(2025, 5, 5),
                'recurring' => true,
                'recurrence_type' => 1,
                'month' => 5,
                'day' => 5,
                'color' => '#3b82f6',
                'is_active' => true,
            ],
            [
                'country_code' => 'GB',
                'title' => 'Spring Bank Holiday',
                'description' => 'Last Monday in May',
                'date' => Carbon::create(2025, 5, 26),
                'recurring' => true,
                'recurrence_type' => 1,
                'month' => 5,
                'day' => 26,
                'color' => '#3b82f6',
                'is_active' => true,
            ],
            [
                'country_code' => 'GB',
                'title' => 'Summer Bank Holiday',
                'description' => 'Last Monday in August (England, Wales, Northern Ireland)',
                'date' => Carbon::create(2025, 8, 25),
                'recurring' => true,
                'recurrence_type' => 1,
                'month' => 8,
                'day' => 25,
                'color' => '#3b82f6',
                'is_active' => true,
            ],
            [
                'country_code' => 'GB',
                'title' => 'Boxing Day',
                'description' => 'Day after Christmas',
                'date' => Carbon::create(2025, 12, 26),
                'recurring' => true,
                'recurrence_type' => 1,
                'month' => 12,
                'day' => 26,
                'color' => '#22c55e',
                'is_active' => true,
            ],

            // ========================================
            // CANADA SCHOOL HOLIDAYS
            // ========================================
            // Note: "New Year's Day" and "Christmas Day" are already in global holidays
            [
                'country_code' => 'CA',
                'title' => 'Good Friday',
                'description' => 'Christian holiday commemorating the crucifixion of Jesus',
                'date' => Carbon::create(2025, 4, 18),
                'recurring' => true,
                'recurrence_type' => 1,
                'month' => 4,
                'day' => 18,
                'color' => '#8b5cf6',
                'is_active' => true,
            ],
            [
                'country_code' => 'CA',
                'title' => 'Victoria Day',
                'description' => 'Celebrates Queen Victoria (Monday before May 25)',
                'date' => Carbon::create(2025, 5, 19),
                'recurring' => true,
                'recurrence_type' => 1,
                'month' => 5,
                'day' => 19,
                'color' => '#3b82f6',
                'is_active' => true,
            ],
            [
                'country_code' => 'CA',
                'title' => 'Canada Day',
                'description' => 'Celebrates Canadian Confederation',
                'date' => Carbon::create(2025, 7, 1),
                'recurring' => true,
                'recurrence_type' => 1,
                'month' => 7,
                'day' => 1,
                'color' => '#ef4444',
                'is_active' => true,
            ],
            [
                'country_code' => 'CA',
                'title' => 'Labour Day',
                'description' => 'Celebrates workers (First Monday in September)',
                'date' => Carbon::create(2025, 9, 1),
                'recurring' => true,
                'recurrence_type' => 1,
                'month' => 9,
                'day' => 1,
                'color' => '#3b82f6',
                'is_active' => true,
            ],
            [
                'country_code' => 'CA',
                'title' => 'Thanksgiving Day',
                'description' => 'Canadian Thanksgiving (Second Monday in October)',
                'date' => Carbon::create(2025, 10, 13),
                'recurring' => true,
                'recurrence_type' => 1,
                'month' => 10,
                'day' => 13,
                'color' => '#f97316',
                'is_active' => true,
            ],
            [
                'country_code' => 'CA',
                'title' => 'Remembrance Day',
                'description' => 'Honors military personnel who died in service',
                'date' => Carbon::create(2025, 11, 11),
                'recurring' => true,
                'recurrence_type' => 1,
                'month' => 11,
                'day' => 11,
                'color' => '#dc2626',
                'is_active' => true,
            ],
            [
                'country_code' => 'CA',
                'title' => 'Boxing Day',
                'description' => 'Day after Christmas',
                'date' => Carbon::create(2025, 12, 26),
                'recurring' => true,
                'recurrence_type' => 1,
                'month' => 12,
                'day' => 26,
                'color' => '#22c55e',
                'is_active' => true,
            ],

            // ========================================
            // AUSTRALIA SCHOOL HOLIDAYS
            // ========================================
            // Note: "New Year's Day" and "Christmas Day" are already in global holidays
            [
                'country_code' => 'AU',
                'title' => 'Australia Day',
                'description' => 'National day of Australia',
                'date' => Carbon::create(2025, 1, 26),
                'recurring' => true,
                'recurrence_type' => 1,
                'month' => 1,
                'day' => 26,
                'color' => '#ef4444',
                'is_active' => true,
            ],
            [
                'country_code' => 'AU',
                'title' => 'Good Friday',
                'description' => 'Christian holiday commemorating the crucifixion of Jesus',
                'date' => Carbon::create(2025, 4, 18),
                'recurring' => true,
                'recurrence_type' => 1,
                'month' => 4,
                'day' => 18,
                'color' => '#8b5cf6',
                'is_active' => true,
            ],
            [
                'country_code' => 'AU',
                'title' => 'Easter Monday',
                'description' => 'Day after Easter Sunday',
                'date' => Carbon::create(2025, 4, 21),
                'recurring' => true,
                'recurrence_type' => 1,
                'month' => 4,
                'day' => 21,
                'color' => '#8b5cf6',
                'is_active' => true,
            ],
            [
                'country_code' => 'AU',
                'title' => 'Anzac Day',
                'description' => 'Honors Australian and New Zealand war veterans',
                'date' => Carbon::create(2025, 4, 25),
                'recurring' => true,
                'recurrence_type' => 1,
                'month' => 4,
                'day' => 25,
                'color' => '#dc2626',
                'is_active' => true,
            ],
            [
                'country_code' => 'AU',
                'title' => 'Queen\'s Birthday',
                'description' => 'Celebrates the birthday of the reigning monarch (Second Monday in June)',
                'date' => Carbon::create(2025, 6, 9),
                'recurring' => true,
                'recurrence_type' => 1,
                'month' => 6,
                'day' => 9,
                'color' => '#3b82f6',
                'is_active' => true,
            ],
            [
                'country_code' => 'AU',
                'title' => 'Boxing Day',
                'description' => 'Day after Christmas',
                'date' => Carbon::create(2025, 12, 26),
                'recurring' => true,
                'recurrence_type' => 1,
                'month' => 12,
                'day' => 26,
                'color' => '#22c55e',
                'is_active' => true,
            ],
        ];

        foreach ($holidays as $holiday) {
            // For recurring holidays, ensure date matches month/day (use a reference year like 2000)
            // The system will calculate the correct date for any year using month/day
            if ($holiday['recurring'] && isset($holiday['month']) && isset($holiday['day'])) {
                // Set date to reference year (2000) - the actual year doesn't matter for recurring holidays
                // The month and day are what matter for recurring holidays
                $holiday['date'] = Carbon::create(2000, $holiday['month'], $holiday['day']);
            }
            
            // Use unique identifier: country_code + title + month + day (for recurring) or country_code + title + date (for fixed)
            $uniqueKey = [
                'country_code' => $holiday['country_code'],
                'title' => $holiday['title'],
            ];
            
            // For recurring holidays, use month and day as part of unique key
            if ($holiday['recurring'] && isset($holiday['month']) && isset($holiday['day'])) {
                $uniqueKey['month'] = $holiday['month'];
                $uniqueKey['day'] = $holiday['day'];
            } else {
                // For fixed holidays, use the date as part of unique key
                $uniqueKey['date'] = $holiday['date'];
            }
            
            PublicHoliday::updateOrCreate(
                $uniqueKey,
                $holiday
            );
        }
    }
}

